# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
